### ISSUE TITLE
proto version mismatch

### ISSUE THREAD

**Issue by swills** [jceel/lib9p#14]
It seems lib9p and qemu disagree about protocol versions:

https://github.com/conclusiveeng/lib9p/blob/master/lib9p.h#L99-L104

```
enum l9p_version {
	L9P_INVALID_VERSION = 0,
	L9P_2000 = 1,
	L9P_2000U = 2,
	L9P_2000L = 3
};
```

vs

https://github.com/qemu/qemu/blob/master/hw/9pfs/9p.h#L98-L101

```
typedef enum P9ProtoVersion {
    V9FS_PROTO_2000U = 0x01,
    V9FS_PROTO_2000L = 0x02,
} P9ProtoVersion;
```

I ran into this when testing lib9p and bhyve with the virtfs from Juniper:

https://github.com/Juniper/virtfs/compare/jnpr/virtfs

Which is right, lib9p or qemu?

**Comment by jceel** [comment]
Hi Steve,

It doesn't matter - Tversion request and Rversion response pass protocol version as string, eg `9P2000.L`. Enums such as `l9p_version` are only used internally by the library, so there is no need for them to agree.

**Comment by swills** [comment]
Ah, I see, thanks! I was missing:

https://github.com/Juniper/virtfs/blob/b03cc743def7d15c6a94205326e27b82f50cd178/sys/dev/virtio/9pnet/client.c#L444
